#!/bin/sh
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
#------------------------------------------------------------------------------

touch case.foam
rm -rf 0 processor*
rm log*

cp -r 0.mapped 0


runApplication decomposePar

runParallel $(getApplication)

#runApplication reconstructPar

#------------------------------------------------------------------------------
