#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication surfaceFeatureExtract

runApplication blockMesh

for i in 1 2 3 4
do
    runApplication -s $i \
        topoSet -dict system/topoSetDict.${i}
    runApplication -s $i \
        refineMesh -dict system/refineMeshDict.${i} -overwrite
done

restore0Dir

runApplication decomposePar

runParallel snappyHexMesh -overwrite

runParallel topoSet -dict system/topoSetDict.5
runParallel refineMesh -dict system/refineMeshDict.5 -overwrite

runParallel setFields
export FOAM_SIGFPE=false
runParallel setExprFields
runParallel setExprBoundaryFields
export FOAM_SIGFPE=true

touch case.foam

#------------------------------------------------------------------------------
