#!/bin/sh
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
#------------------------------------------------------------------------------

echo "Run python for inizialization"
python3 uProfile.py

runApplication blockMesh

restore0Dir

runApplication setFields

FOAM_SIGFPE=false setExprFields > log.setExprFields

touch case.foam

runApplication $(getApplication)

#------------------------------------------------------------------------------
