#!/bin/bash

echo Preparing 0 folder...
cp -r 0.org 0

echo blockMesh meshing...
blockMesh > blockMesh.log

echo Setting the fields...
#setFields > setFields.log
setOla > setOla.log

echo Running...
olaFlow > olaFlow.log

#echo Simulation complete.

